spring:
  application:
    name: blockchain-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/blockchain
    username: ${DB_USER:admin}
    password: ${DB_PASS:admin}
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8080/auth}/realms/medical

server:
  port: 8082
  servlet:
    context-path: /api/blockchain

# Blockchain configuration
blockchain:
  networkConfigPath: ${NETWORK_CONFIG_PATH:blockchain/network-config/connection-org1.yaml}
  walletPath: ${WALLET_PATH:blockchain/wallet}
  userName: ${BLOCKCHAIN_USER:admin}
  channelName: ${CHANNEL_NAME:mychannel}
  chaincodeName: ${CHAINCODE_NAME:medical-chaincode}

# Keycloak settings
keycloak:
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8080/auth}
  realm: medical
  resource: blockchain-service
  public-client: true

# Logging settings
logging:
  level:
    root: INFO
    com.medical: DEBUG
    org.hyperledger.fabric: INFO 